{
 "title": "S.M.A.R.T disk monitoring for Prometheus Dashboard",
 "description": "Smartmon Texfile node_exporter Dashboard",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(smartctl_version, instance)"
   },
   {
    "name": "device_model",
    "query": "label_values(smartctl_device, model_name)"
   },
   {
    "name": "device",
    "query": "label_values(smartctl_device, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unhealthy Disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(smartctl_device_smart_status{instance=\"$instance\"}) - sum(smartctl_device_smart_status{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(smartmon_reallocate_nand_blk_cnt_raw_value) + sum( smartmon_reallocated_sector_ct_raw_value) + sum(smartmon_reallocated_event_count_raw_value) + sum(smartmon_raw_read_error_rate_raw_value) + sum(smartmon_current_pending_sector_raw_value) + sum(smartmon_offline_uncorrectable_raw_value) + sum(smartmon_udma_crc_error_count_raw_value) + sum(smartmon_seek_error_rate_raw_value) + sum(smartmon_spin_retry_count_raw_value) + sum(smartmon_multi_zone_error_rate_raw_value)"
    }
   ]
  },
  {
   "title": "Active devices",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(smartmon_device_active)" }
   ]
  },
  {
   "title": "Temperature_Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(smartctl_device_temperature{instance=\"$instance\", device=\"$device\"}) by (instance, device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Temperature_Threshold",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "smartctl_device_attribute{instance=\"$instance\", device=\"$device\", attribute_name=\"Temperature_Celsius\", attribute_value_type=\"thresh\"}"
    }
   ]
  },
  {
   "title": "Temperture_Gauge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "smartctl_device_temperature{instance=\"$instance\", device=\"$device\" }",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "content": "<p></p>\n<p style=\"text-align: center;font-size: x-large;face:arial;\">__________ Wear and Tear __________</p>"
  },
  {
   "title": "Power_On_Hours",
   "type": "gauge",
   "description": "yellow after 1 year\nred after 1 1/2 years",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "smartctl_power_on_seconds{instance=\"$instance\", device=\"$device\"}",
     "legendFormat": " {{device}}"
    }
   ]
  },
  {
   "title": "Power_Cycle_Count",
   "type": "gauge",
   "description": "Number of times disk was turned on",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "smartctl_device_power_cycle_count{instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "content": "<p></p>\n<p style=\"text-align: center;font-size: x-large;face:arial;\">__________ SSD Specific Values __________</p>"
  },
  {
   "title": "Remaining_Lifetime",
   "type": "gauge",
   "description": "Estimated remaining lifetime.\nBased on amount of written data.\n(Very vague one flash chip can be witten 10 000 times)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "smartctl_device_attribute{instance=\"$instance\", device=\"$device\", attribute_name=\"Load_Cycle_Count\", attribute_value_type=\"raw\"} / smartctl_device_attribute{instance=\"$instance\", device=\"$device\", attribute_name=\"Load_Cycle_Count\", attribute_value_type=\"thresh\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Host_Sector_Write (TB)",
   "type": "singlestat",
   "description": "One block typically have 256 to 4096 B \n(most likely 4096)\nCrucial BX500 (ETA 40TB)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "smartctl_device_attribute{instance=\"$instance\", device=\"$device\", attribute_name=\"Total_LBAs_Written\"} * 4096/1024/1024/1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "content": "<p></p>\n<p style=\"text-align: center;font-size: x-large;face:arial;\">__________ HDD Specific Values __________</p>"
  },
  {
   "title": "Spin_Up_Time",
   "type": "graph",
   "description": "Average time to spin up disk. (in ms)\nHigh values indicate problems with the motor.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "smartctl_device_attribute{instance=\"$instance\", attribute_name=\"Spin_Up_Time\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Power_Off_Retract_Count",
   "type": "gauge",
   "description": "Number of unexpected power outages (no correct shutdown) \nThis kind of shutdown lowers the lifetime of a disk way more than a clean shutdown",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "smartctl_device_attribute{instance=\"$instance\", device=\"$device\", attribute_name=\"Power-Off_Retract_Count\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Start_Stop_Count",
   "type": "gauge",
   "description": "Counts start/stop events.\nHigh values indicate high wear.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "smartctl_device_attribute{instance=\"$instance\", device=\"$device\", attribute_name=\"Start_Stop_Count\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Load_Cycle_Count",
   "type": "gauge",
   "description": "Number times the head was placed in the parking area.\nMostly mobile disks.\n300000 times is intended.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "smartctl_device_attribute{instance=\"$instance\", device=~\"$device\", attribute_name=\"Load_Cycle_Count\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Device_Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "targets": [
    { "expr": "smartctl_device" }
   ]
  }
 ]
}