name: nixos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: nixos
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - name: Build NixOS image
        id: build-nixos-image
        run: |
          nix-shell -p nixos-generators --run "nixos-generate -f iso -c ${{ github.workspace }}/nixos/configuration-installer.nix -o result"
          echo "artifact_build_time=$(date -u +%Y-%m-%dT%H_%M_%S)" >> $GITHUB_OUTPUT
          echo "artifact_digest=$(readlink result | cut -d '/' -f 4 | cut -d '-' -f 1)" >> $GITHUB_OUTPUT
          echo "artifact_path=$(readlink result)" >> $GITHUB_OUTPUT
      - uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          tag: "${{ steps.build-nixos-image.outputs.artifact_build_time }}-${{ steps.build-nixos-image.outputs.artifact_digest }}"
          commit: main
          artifacts: "${{ steps.build-nixos-image.outputs.artifact_path }}/iso/nixos.iso"
