name: tofu

on:
  pull_request:
    paths:
      - 'tf/**'
  push:
    branches:
      - main
    paths:
      - 'tf/**'
  schedule:
    - cron: 0 19 * * 2

jobs:
  tofu:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: opentofu/setup-opentofu@v1
      - run: tofu fmt -recursive -diff
      - run: tofu init
      - run: tofu validate
